# Generated by Django 4.2.3 on 2023-07-11 11:10

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контакты компании',
                'verbose_name_plural': 'Контакты компании',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robots', models.TextField(blank=True, verbose_name='robots.txt')),
                ('favicon', models.ImageField(blank=True, upload_to='favicon', verbose_name='Favicon')),
                ('extra_head_html', models.TextField(blank=True)),
                ('extra_body_html', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TelegramBotCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, verbose_name='Токен')),
                ('kind', models.CharField(choices=[('logs', 'Для логов'), ('order', 'Для заказов')], max_length=5, unique=True, verbose_name='Назначение')),
                ('chat_id', models.CharField(help_text='Куда отправлять', max_length=15, verbose_name='Id чата')),
            ],
            options={
                'verbose_name': 'Данные от телеграм бота',
                'verbose_name_plural': 'Данные от телеграм ботов',
            },
        ),
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('show_in_sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, verbose_name='Keywords')),
                ('menu_title', models.CharField(blank=True, max_length=200, verbose_name='Название в меню')),
                ('menu_position', models.IntegerField(blank=True, verbose_name='Позиция в меню')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Контент')),
                ('is_generic_page', models.BooleanField(blank=True, default=True, help_text='Снять галочку, если страница обрабатывается кастомной view', verbose_name='Является стандартной страницей')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
