# Generated by Django 4.2.3 on 2023-07-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedbackrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='bitrix_lead_title_template',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='bitrix_webhook_url',
        ),
    ]
