# Generated by Django 4.2.3 on 2023-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_sitesettings_bitrix_lead_title_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('post', models.CharField(blank=True, max_length=256, verbose_name='Должность')),
                ('photo', models.FileField(upload_to='masters', verbose_name='Фото')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
