# Generated by Django 4.2.3 on 2023-08-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_masters_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('index', 'Index'), ('price', 'Price')], max_length=10)),
            ],
        ),
    ]
