# Generated by Django 4.2.3 on 2023-08-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seotext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeoText',
        ),
    ]
