# Generated by Django 4.2.3 on 2023-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_seotext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=20, verbose_name='Номер услуги')),
                ('service_name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цены')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('details', models.TextField(blank=True, verbose_name='Под описание')),
            ],
        ),
        migrations.AddField(
            model_name='textpage',
            name='price_description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Price description'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='price_money',
            field=models.CharField(blank=True, max_length=200, verbose_name='money'),
        ),
        migrations.AddField(
            model_name='textpage',
            name='price_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Price title'),
        ),
    ]
