# Generated by Django 4.2.3 on 2023-08-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_textpage_price_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
