# Generated by Django 4.2.3 on 2023-08-31 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_service_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер услуги'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание отзыва')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masters', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
