# Generated by Django 4.2.3 on 2023-08-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_service_service_number_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_review', models.CharField(max_length=256, verbose_name='ФИО')),
                ('post_review', models.CharField(blank=True, max_length=256, verbose_name='Время')),
                ('photo_review', models.FileField(upload_to='client', verbose_name='Фото')),
                ('description_review', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
