# Generated by Django 4.2.3 on 2023-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_service_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_number',
            field=models.IntegerField(),
        ),
    ]
