# Generated by Django 4.2.3 on 2023-08-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_service_service_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_number',
            field=models.CharField(max_length=20, verbose_name='Номер услуги'),
        ),
    ]
