# Generated by Django 4.2.3 on 2023-08-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_service_service_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description_review',
            new_name='review_description',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name_review',
            new_name='review_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='photo_review',
            new_name='review_photo',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='post_review',
            new_name='review_post',
        ),
    ]
