# Generated by Django 4.2.3 on 2023-08-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='details',
        ),
        migrations.CreateModel(
            name='ServiceDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Пункт')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
            options={
                'verbose_name': 'Описание услуги',
                'verbose_name_plural': 'Описания услуг',
            },
        ),
    ]
