# Generated by Django 4.2.3 on 2023-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_webhook_url', models.URLField(blank=True, default='', help_text='Оставьте пустым, чтобы отключить интеграцию с битрикс')),
                ('bitrix_lead_title_template', models.CharField(help_text='Можно использовать просто строку, или шаблон django</br>Пример: "Заявка на обратную связь от {{ phone }}"</br>Можно использовать {% if ... %} {% endif %}</br>Доступные переменные: first_name, last_name, phone, email', max_length=64, verbose_name='Шаблон заголовка лида в битрикс')),
            ],
        ),
    ]
