# Generated by Django 4.2.3 on 2023-07-19 11:53

from django.db import migrations, models
import integrations.bitrix.models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bitrix_custom_fields_map',
            field=models.JSONField(default=integrations.bitrix.models.get_default_bitrix_custom_fields_map, help_text='Формат: {"internal_field_key": "UF_CRM_1689233493499"}</br>Где internal_field_key - внутреннее имя, UF_CRM_1689233493499 - имя поля в Битриксе</br>', verbose_name='Маппинг полей'),
        ),
    ]
